version: '3.5'
services:

  worker:
    build: .
    restart: "no"
    env_file: &envfile
      - environment.env
    command: celery -A api worker -l info -n worker10.%h
    volumes:
      - ./api:/api
    networks:
      - my-proxy-net

networks:
  my-proxy-net:
    external:
      name: custom_network
